### ISSUE TITLE
PHP 2024 Documentation Roadmap

### ISSUE THREAD

**Issue by Girgias** [php/doc-en#3240]
These are ideas that we want to achieve as part of @ThePHPF in 2024:

- [ ] Constant linking (massive thank you to @haszi for doing the necessary work on the Renderer for this)
- [ ] Improve call-out to contribute to the docs to be more like MDN which has it at the bottom of the page instead of hidden in the top right
- [ ] Rewrite the "Edited-by" section of the documentation
- [ ] Allow executing examples via [3v4l.org](https://3v4l.org/) (in collaboration with @SjonHortensius)
- [ ] Investigate adding a "Last Edited" time for individual documentation pages
- [ ] Triage user notes
- [ ] Implement a support policy for what PHP versions the documentation covers and for how long

**Comment by SjonHortensius** [comment]
Making examples executable would ideally be done by storing the correct script link somewhere. Alternatively a new `POST` could be done to the correct endpoint containing the full example code - 3v4l will then forward the user to the correct script. I'd be happy to help with supporting the implementation from the 3v4l side

**Comment by Girgias** [comment]
I think there will need to be some changes in PhD to tie the example content to the output box if it exists, we might also need to limit it to parts of the documentation that does not refer to PECL extensions, as I don't think those are on 3v4l?

**Comment by kamil-tekiela** [comment]
Is there any plan to split these points into separate issues with better guidance to contributors on what needs to be done? Or is this just an announcement of what kind of work is already being carried out?

**Comment by Girgias** [comment]
We can split them up into separate issues, the constant linking one is *more or less* "done" as there has been good progress on this. User notes is something where one needs access to the underlying database so difficult to contribute.

The rest could be their own issues

**Comment by pronskiy** [comment]
Folks, I've created a #3259 to continue "Allow executing examples via [3v4l.org](https://3v4l.org/)" implementation discussion.

**Comment by kocsismate** [comment]
@Girgias What does "Constant linking" exactly mean? Is it that the constants which are documented somewhere else than "predefined constant" pages should be moved to one of these pages and they should be linked wherever they are referenced from? Is documenting the rest of the missing constants/functions/methods too big of a project?

**Comment by Girgias** [comment]
> @Girgias What does "Constant linking" exactly mean? Is it that the constants which are documented somewhere else than "predefined constant" pages should be moved to one of these pages and they should be linked wherever they are referenced from? Is documenting the rest of the missing constants/functions/methods too big of a project?

It's just to have `<constant>` tags create a link to the constant definition, similarly to how `<function>` does this for functions. It _might_ require moving constants to the more standard pages, but not necessarilly.

**Comment by haszi** [comment]
>     * [ ]  Rewrite the "Edited-by" section of the documentation

Do https://github.com/php/doc-en/pull/3467 and https://github.com/php/doc-en/pull/3468 address this in part or whole?

**Comment by haszi** [comment]
>     * [ ]  Implement a support policy for what PHP versions the documentation covers and for how long

This item is addressed by the following PR: https://github.com/php/doc-en/pull/3700

**Comment by Girgias** [comment]
I updated the text.

**Comment by DanielRuf** [comment]
Are there plans to add some "edit this page on GitHub"? Because it's a bit hard to find the documentation repo and correct file from the original documentation links.

**Comment by Girgias** [comment]
> Are there plans to add some "edit this page on GitHub"? Because it's a bit hard to find the documentation repo and correct file from the original documentation links.

![image](https://github.com/user-attachments/assets/4d362c65-bbe6-44c4-bc35-ebbba030ec38)

 This is already the case, so I would like to know in what way it is hard?
Note that translations may not have the page translated and so use the English version as a backup, but I don't know if the callout links properly to doc-en. Maybe @haszi knows.

**Comment by DanielRuf** [comment]
My bad, I was looking at the wrong page @Girgias.

Regarding "hard", the other translations are missing some guidance (to be precise: a readme file) and do not link to the repo for the english / original version:

* https://github.com/php/doc-de/
* https://github.com/php/doc-fr/
* https://github.com/php/doc-en/

And some repos have a different readme file, which is a bit inconsistent.

I think it would be at least helpful to link to the original version / repo in the description:

![image](https://github.com/user-attachments/assets/412737b1-e889-4d7c-acbb-f2b652ccba2f)

Repo descriptions support links:
![image](https://github.com/user-attachments/assets/67c44ab1-b5a8-464b-acc7-da350fbb036f)

**Comment by haszi** [comment]
> ...but I don't know if the callout links properly to doc-en. Maybe @haszi knows.

I just checked and it doesn't.

**Comment by Girgias** [comment]
> Regarding "hard", the other translations are missing some guidance (to be precise: a readme file) and do not link to the repo for the english / original version:
> 
>     * https://github.com/php/doc-de/
> 
>     * https://github.com/php/doc-fr/
> 
>     * https://github.com/php/doc-en/
> 
> 
> And some repos have a different readme file, which is a bit inconsistent.
> 

Each translation operates independently, I'm only involved in doc-fr (and even then less so nowadays) and I wrote the README to deal with specificities of it and have a tutorial in a more convenient location than doc.php.net.

So in that case, you need to open an issue on the relevant repo.

**Comment by jimwins** [comment]
> Each translation operates independently, I'm only involved in doc-fr (and even then less so nowadays) and I wrote the README to deal with specificities of it and have a tutorial in a more convenient location than doc.php.net.
> 
> So in that case, you need to open an issue on the relevant repo.

Somewhat related to that, I prototyped a version of the Makefile/Docker setup for doing local builds that works in the translations just like the one in `doc-en`. Like that one, it will use adjacent `doc-base`, `en`, and `phd` repositories if they are available, otherwise it builds them into the Docker image.

https://github.com/php/doc-fr/pull/1534
