### ISSUE TITLE
Add documentation about missing functions introduced in PHP 7 cycle.

### ISSUE THREAD

**Issue by Girgias** [php/doc-en#663]
Found via the upgrading docs

 - [x]  PHP 7.3
   - [x] `fpm_get_status()` (#1420)
   - [x]  `net_get_interfaces()` (#847)
 - [x] PHP 7.4
   - [x] `get_mangled_object_vars()` (#953)
   - [x] `imagecreatefromtga()` (#950)
   - [x] `pcntl_unshare()` (#958)
