### ISSUE TITLE
PHP 8.0 documentation tracker

### ISSUE THREAD

**Issue by Girgias** [php/doc-en#674]
Pages which need to be added/modified for complete documentation of PHP 8.0:

Based of the migration guide: https://www.php.net/manual/en/migration80.php (formally php/doc-en#170)

## Core:

- [x] New features:
   - [x] Type declarations (https://github.com/php/doc-en/pull/174)
     - [x] Union types 
     - [x] mixed
     - [x] static return
  - [x] Constructor Promotion (https://github.com/php/doc-en/pull/188)
  - [x] match expressions (https://github.com/php/doc-en/pull/206)
     - [x] UnhandledMatchError
  - [x] Named arguments allow passing arguments to a function based on the parameter name, rather than the parameter position. (https://github.com/php/doc-en/pull/251)
  - [x] Attributes (https://github.com/php/doc-en/pull/254)
  - [x] Null-safe operator (https://github.com/php/doc-en/pull/244)
  - [x] Stringable interface (https://github.com/php/doc-en/pull/478)
  - [x] WeakMap (core) (https://github.com/php/doc-en/pull/479)
  - [x] $object::class (https://github.com/php/doc-en/pull/239)
  - [x] Catch without variable (https://github.com/php/doc-en/pull/238)
  - [x] traits can now have abstract private methods and they are validated against the implementation provided in the using class, according to our usual inheritance rules. (https://github.com/php/doc-en/pull/476)
  - [x] ValueError (https://github.com/php/doc-en/pull/205)
  - [x] DateTime format specifier `p` (https://github.com/php/doc-en/pull/230)
- [x] Modified features:
  - [x] throw expression (https://github.com/php/doc-en/pull/238)
  - [x]  &new; and &instanceof; can now be used with arbitrary expressions
  - [x] trailing commas in parameter lists (https://github.com/php/doc-en/pull/241)
  - [x] private methods do not enforce inheritance rules on child classes any more (except __construct) (https://github.com/php/doc-en/pull/481)
  - [x] Numeric strings (https://github.com/php/doc-en/pull/215)
    - [x] Comparison
    - [x] When a string is considered numeric
  - [x] Float to string conversion (https://github.com/php/doc-en/pull/215)
  - [x] Operator precedence
    - [x] Concatenation (011596bcff82477d121de738e6cf83bd2b13bb40)
- [x] Deprecated
   - [x] Optional args after mandatory ones (https://github.com/php/doc-en/pull/251, https://github.com/php/doc-en/pull/270)
   - [x] The ability to define case-insensitive constants has been removed. The third argument to define() may no longer be true. 
## Classes
- [x] New classes
   - [x] Tokenizer: PhpToken (https://github.com/php/doc-en/pull/272)
   - [x] DOM
      - [x] DOMParentNode (#1025)
      - [x] DOMChildNode (#1025)
- [x] Resource to Opaque Object conversions:
   - [x] `CurlHandle` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `CurlMultiHandle` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `CurlShareHandle` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `EnchantBroker` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `EnchantDictionary` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `GdImage` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `OpenSSLCertificate` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `OpenSSLCertificateSigningRequest` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `OpenSSLAsymmetricKey` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `Shmop` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `Socket` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `AddressInfo` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `SysvMessageQueue` (#1020)
   - [x] `SysvSemaphore` (#1020)
   - [x] `SysvSharedMemory` (#1020)
   - [x] `XmlParser` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `XMLWriter` (https://github.com/php/doc-en/commit/c31630ca23d219c758a8b580e1d583103e97e377)
   - [x] `InflateContext` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
   - [x] `DeflateContext` (https://github.com/php/doc-en/commit/5f8047c12b4078a6f686b2b0589e9284c47bf155)
- [x] Renamed classes (https://github.com/php/doc-en/pull/246)
  - [x] `OCI-Lob` to `OCILob`
  - [x] `OCI-Collection` to `OCICollection`

## Functions/Methods:
- [x] New functions
  - [x] Standard
    - [x] `fdiv()` (https://github.com/php/doc-en/pull/258)
    - [x] `get_debug_type()` (https://github.com/php/doc-en/pull/591)
    - [x] `get_resource_id()` (https://github.com/php/doc-en/pull/227)
    - [x] `str_contains()` (https://github.com/php/doc-en/pull/216)
    - [x] `str_start_with()` (https://github.com/php/doc-en/pull/217)
    - [x] `str_ends_with()` (https://github.com/php/doc-en/pull/217)
  - [x] Date and Time
    - [x] `DateTime::createFromInterface()` (https://github.com/php/doc-en/pull/257)
    - [x] `DateTimeImmutable::createFromInterface()` (https://github.com/php/doc-en/pull/257)
  - [x] GD
     - [x] `imagegetinterpolation()` (https://github.com/php/doc-en/commit/0ebd26c45ca444f08665c8b941f8647970ae5f8a)
  - [x] LDAP
     - [x] `ldap_count_references()` (#733)
  - [x] OpenSSL (https://github.com/php/doc-en/commit/ad0175ba440b2cb9f22eefc2ca756b885ed79d35)
     - [x] `openssl_cms_encrypt()`
     - [x] `openssl_cms_decrypt()`
     - [x] `openssl_cms_read()`
     - [x] `openssl_cms_sign()`
     - [x] `openssl_cms_verify()`
  - [x] ZIP
     - [x] `ZipArchive::setProgressCallback()` (https://github.com/php/doc-en/pull/228)
     - [x] `ZipArchive::setCancelCallback()` (https://github.com/php/doc-en/pull/228)
- [x] Modified functions
  - [x] `printf` and friends (https://github.com/php/doc-en/pull/268)
  - [x] `imagepolygon` and friends (https://github.com/php/doc-en/commit/de8b75ccb611a97e67ac91ff51c4435b128656f2) 
- [x] Deprecated
  - [x] PGSQL aliases (https://github.com/php/doc-en/commit/7a81e2b77d85a029d033f87d8ad306efb508a16f)
  - [x] Enchant (https://github.com/php/doc-en/commit/94f2c273f0bb214580b3cba17273f79e8cc2cb25)
    - [x] `enchant_broker_set_dict_path()`
    - [x] `enchant_broker_get_dict_path()`
    - [x] `enchant_dict_add_to_personal()`
    - [x] `enchant_broker_free()`
  - [x] `libxml_disable_entity_loader()`
  - [x] Procedural ZIP API (https://github.com/php/doc-en/commit/e7278889420140e0af5df90efe9f1cb63eb63842)
  - [x] Reflection
     - [x] `ReflectionFunction::isDisabled()`
     - [x] `ReflectionParameter::getClass()`
     - [x] `ReflectionParameter::isArray()`
     - [x] `ReflectionParameter::isCallable()`

## Constants:
- [x] New
  - [x] Filter
     - [x] FILTER_VALIDATE_BOOL (https://github.com/php/doc-en/pull/676)
  - [x] Intl
    - [x] IntlDateFormatter::RELATIVE_FULL (https://github.com/php/doc-en/pull/267)
    - [x] IntlDateFormatter::RELATIVE_LONG (https://github.com/php/doc-en/pull/267)
    - [x] IntlDateFormatter::RELATIVE_MEDIUM (https://github.com/php/doc-en/pull/267)
    - [x] IntlDateFormatter::RELATIVE_SHORT (https://github.com/php/doc-en/pull/267)
  - [x] Reflection (https://github.com/php/doc-en/commit/98df2cf9a939729d73adee1484ec05929c74c98b)
    - [x] ReflectionClassConstant::IS_PUBLIC
    - [x] ReflectionClassConstant::IS_PROTECTED
    - [x] ReflectionClassConstant::IS_PRIVATE
  - [x] OpenSSL (https://github.com/php/doc-en/commit/1ae5ae975a3b0cf1e1e64401b24010511b6dba4d)
     - [x] ` OPENSSL_ENCODING_DER`
     - [x] `OPENSSL_ENCODING_SMIME`
     - [x] `OPENSSL_ENCODING_PEM`
- [x] Deprecated
  - [x] Enchant (https://github.com/php/doc-en/commit/94f2c273f0bb214580b3cba17273f79e8cc2cb25)
    - [x] `ENCHANT_MYSPELL`
    - [x] `ENCHANT_ISPELL`
  - [x] PGSQL_LIBPQ_VERSION_STR (https://github.com/php/doc-en/commit/fa7cb182a0ef04a3ecef2f9a0d6ae99e77201330)

**Comment by flow-control** [comment]
I added some docs about the `FILTER_VALIDATE_BOOL` alias via #676

**Comment by hluup** [comment]
Array sort functions are stable since PHP 8, but right now the info box indicates that they are unstable. Here's a pull request that clarifies that - https://github.com/php/doc-en/pull/539

**Comment by mallardduck** [comment]
I believe that when #1155 and #1025 are complete and merged in then all the PHP 8.0 docs are completed and we're all caught up here.

**Comment by kocsismate** [comment]
Also, we shouldn't forget about finishing the documentation of the function signature changes (https://github.com/php/doc-en/labels/method%20synopsis)

**Comment by mallardduck** [comment]
@kocsismate i was mostly going off what items are in the top post as unchecked so far.
I do see the discussion about those being part of the 8.0 docs but not on the to-do. So it does seem that those should be merged - yet they may not be blockers for the PRs i mentioned which could close out the remaining checklist items and this issues remaining listed tasks.

**Comment by kocsismate** [comment]
> yet they may not be blockers for the PRs i mentioned which could close out the remaining checklist items and this issues remaining listed tasks.

Yeah, they are not a blocker in any way for the mentioned PRs: I just wanted to highlight that even if the tasks are done in this ticket, a bunch of PHP 8.0 related PRs are still waiting for review. :(

**Comment by saundefined** [comment]
It seems all tasks are done, issue can be closed? =)

**Comment by kitrio** [comment]
> It seems all tasks are done, issue can be closed? =) 


https://www.php.net/manual/en/reflectionproperty.construct.php
https://www.php.net/manual/en/reflectionproperty.getattributes.php
https://www.php.net/manual/en/reflectionproperty.clone.php
https://www.php.net/manual/en/reflectionproperty.getdeclaringclass.php
https://www.php.net/manual/en/reflectionproperty.getmodifiers.php
https://www.php.net/manual/en/reflectionproperty.getname.php
https://www.php.net/manual/en/reflectionproperty.tostring.php


These pages show

"Warning
This function is currently not documented; only its argument list is available."

**Comment by Girgias** [comment]
> > It seems all tasks are done, issue can be closed? =)
> 
> https://www.php.net/manual/en/reflectionproperty.construct.php https://www.php.net/manual/en/reflectionproperty.getattributes.php https://www.php.net/manual/en/reflectionproperty.clone.php https://www.php.net/manual/en/reflectionproperty.getdeclaringclass.php https://www.php.net/manual/en/reflectionproperty.getmodifiers.php https://www.php.net/manual/en/reflectionproperty.getname.php https://www.php.net/manual/en/reflectionproperty.tostring.php
> 
> These pages show message
> 
> "Warning This function is currently not documented; only its argument list is available."

Please open a new issue, as this is not specific to changes introduced by PHP 8.0.

**Comment by Girgias** [comment]
Thank you everyone who participated in documentating the changes for 8.0!
