### ISSUE TITLE
[PHP 8.1] Resource to Object Migration

### ISSUE THREAD

**Issue by saundefined** [php/doc-en#972]
### [Resource to Object Migration](https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.resource2object)

- [x] PgSQL functions (`PgSql\Connection`, `PgSql\Result`, `PgSql\Lob`) #1009
- [x] PSpell functions (`PSpell\Dictionary`, `PSpell\Config`) #976
- [x] LDAP functions (`LDAP\Connection`, `LDAP\Result`, `LDAP\ResultEntry`) #975
- [x] FileInfo functions #985
- [x] IMAP functions #971
- [x] FTP functions #967

**Comment by mumumu** [comment]
@saundefined I want to help this work and am trying to change `PSpell functions`. Do you already work on it?

**Comment by saundefined** [comment]
@mumumu Thanks! Haven't started yet

**Comment by mumumu** [comment]
> @mumumu Thanks! Haven't started yet

OK. I will assign myself to `PSpell` functions.
