### ISSUE TITLE
PHP 8.1 documentation tracker

### ISSUE THREAD

**Issue by Girgias** [php/doc-en#980]
Pages which need to be added/modified for complete documentation of PHP 8.1.

Based of the migration guide: https://www.php.net/manual/en/migration81.php

This is currently still heavily a work in progress.

## Core:

- [x] New features:
   - [x] Type declarations
     - [x] Intersection types (#982)
     - [x] never (#889)
  - [x] Integer Octal Literal Prefix (#1091)
  - [x] Array Unpacking with String Keys (#1171)
  - [x] Named Argument After Argument Unpacking (#1329)
    * No RFC. related PR -> https://github.com/php/php-src/pull/7009
  - [x] full-path Key for File Uploads (#1130)
  - [x] Enumerations (#960)
  - [x] Fibers (#1096)
  - [x] First Class Callable Syntax (#1176)
  - [x] new in Initializers (#1327)
  - [x] Readonly properties (#1047)
  - [x] Final class constants (#1041)
- [x] Deprecated
   - [x] Implementing Serializable without __serialize() and __unserialize() (#1141)
   - [x] #1554
   - [x] Implicit incompatible float to int conversions (#1528)
   - [x] Calling a static element on a trait (#1330)
   - [x] Returning by reference from a void function (#1127)
   - [x] Autovivification from false (#1126)
- [x] BC Break
   - [x] $GLOBALS Access Restrictions (#1147)
   - [x] Usage of static Variables in Inherited Methods (#1549)
   - [x] Return Type Compatibility with Internal Classes (#1560)
- [x] Other Changes
   - [x] ReflectionProperty::setAccessible() and ReflectionMethod::setAccessible() no longer have an effect. (https://github.com/php/doc-en/commit/7b6a20ed5d1f1bec158b0c57b69bf021a9ed2799)

## Classes
- [x] New classes
   - [x] IntlDatePatternGenerator (#1026)
   - [x] ReflectionIntersectionType (#1027)
   - [x] CURLStringFile (#1154)
- [x] Resource to Opaque Object conversions (#972)

## Functions/Methods:
- [x] New functions
  - [x] Core
    - [x] `array_is_list()` (#986)
  - [x] Standard
    - [x]  `fsync()` (#1002)
    - [x]  `fdatasync()` (#1002)
  - [x] GD
     - [x] `imagecreatefromavif()` (#983)
     - [x] `imageavif()` (#983)
   - [x] MySQLi
     - [x] ``mysqli_result::fetch_column()`` (#776)
   - [x] `pcntl_rfork()` (#1033)
   - [x] ``ReflectionFunctionAbstract::getClosureUsedVariables()`` (#1032)
   - [x] Sodium
     - [x] XChaCha20
        - [x] ``sodium_crypto_stream_xchacha20()`` (#1045)
        - [x] ``sodium_crypto_stream_xchacha20_keygen()`` (#1045)
        - [x] ``sodium_crypto_stream_xchacha20_xor()`` (#1045)
     - [x] Ristretto255
        - [x] ``sodium_crypto_core_ristretto255_add()`` (#1051)
        - [x] ``sodium_crypto_core_ristretto255_from_hash()`` (#1051)
        - [x] ``sodium_crypto_core_ristretto255_is_valid_point()`` (#1051)
        - [x] ``sodium_crypto_core_ristretto255_random()`` (#1051)
        - [x] ``sodium_crypto_core_ristretto255_scalar_add()`` (#1051)
        - [x] ``sodium_crypto_core_ristretto255_scalar_complement()`` (#1051)
        - [x] ``sodium_crypto_core_ristretto255_scalar_invert()`` (#1051)
        - [x] ``sodium_crypto_core_ristretto255_scalar_mul()`` (#1051)
        - [x] ``sodium_crypto_core_ristretto255_scalar_negate()`` (#1051)
        - [x] ``sodium_crypto_core_ristretto255_scalar_random()`` (#1051)
        - [x] ``sodium_crypto_core_ristretto255_scalar_reduce()`` (#1051)
        - [x] ``sodium_crypto_core_ristretto255_scalar_sub()`` (#1051)
        - [x] ``sodium_crypto_core_ristretto255_sub()`` (#1051)
        - [x] ``sodium_crypto_scalarmult_ristretto255()`` (#1051)
        - [x] ``sodium_crypto_scalarmult_ristretto255_base()`` (#1051)
- [x] Modified functions
  - [x] `fputcsv()` and `SplFileObject::fputcsv()` (#978)
  - [x] Hash (WIP) (#1215 #981)
  - [x] ``mysqli_stmt::execute()`` (#987)
- [x] Deprecated
  - [x] ctype: Verifying non-string arguments (#1179)
  - [x] Date
      - [x] ``date_sunrise()`` (#981)
      - [x] ``date_sunset()`` (#981)
      - [x] ``strptime()`` (#981)
      - [x] ``strftime()`` (#1164)

## Constants:
- [x] New
  - [x] POSIX
     - [x] POSIX_RLIMIT_KQUEUES (#436)
     - [x] POSIX_RLIMIT_NPTS (#436)
  - [x] cURL
    - [x] CURLOPT_DOH_URL (#1039)
    - [x] CURLOPT_ISSUERCERT_BLOB (#1039)
    - [x] CURLOPT_PROXY_ISSUERCERT (#1039)
    - [x] CURLOPT_PROXY_ISSUERCERT_BLOB (#1039)
    - [x] CURLOPT_PROXY_SSLCERT_BLOB (#1039)
    - [x] CURLOPT_PROXY_SSLKEY_BLOB (#1039)
    - [x] CURLOPT_SSLCERT_BLOB (#1039)
    - [x] CURLOPT_SSLKEY_BLOB (#1039)
  - [x] MySQLI
    - [x] MYSQLI_REFRESH_REPLICA (#1006)
  - [x] Sockets
    - [x] SO_ACCEPTFILTER (#656)
    - [x] SO_DONTTRUNC (#1018)
    - [x] SO_WANTMORE (#1018)
    - [x] SO_MARK (#656)
    - [x] TCP_DEFER_ACCEPT (#1018)
- [x] Deprecated
  - [x] IMAP
     - [x] NIL  (#981)

**Comment by AllenJB** [comment]
It's not in the list (probably due to the lack of existing documentation on it!), but I've updated my PR for the FPM status page to include the new openmetrics format: https://github.com/php/doc-en/pull/738

**Comment by njames** [comment]
Hey there ... I saw this linked from the @php_official twitter and I thought I would love to assist in any way I can but the onboarding of a new documentor is a tad opaque. 

I have close this repo and installed phd (updating pear in the process) but the very sparse README is leaving me lost. 

Is there "Getting started with being a PHP Documentor for Dummies" link somewhere?

**Comment by njames** [comment]
After a little more digging I found http://doc.php.net/tutorial/local-setup.php :+1:

**Comment by Irker** [comment]
Hello! Can we add the `CurlStringFile` to the list?

**Comment by saundefined** [comment]
> Hello! Can we add the `CurlStringFile` to the list?

Thanks! Done

**Comment by mumumu** [comment]
> Hello! Can we add the CurlStringFile to the list?

Oh. I already added in #1154, sorry... @Irker

**Comment by Irker** [comment]
@mumumu  No, my message was only about adding CurlStringFile to the TODO list for documentation. So please restore your PR. And thank you!

**Comment by mumumu** [comment]
@Irker OK, I restored my PR, thank you! Please reveiew #1154 if you would like.

**Comment by mallardduck** [comment]
I feel like this PR technically is completing documentation that was only done as stubs for PHP 8.0. However I think it'd be worth it to have this PR which documents the `ReflectionClass::getAttributes()` method in this tracker.

https://github.com/php/doc-en/pull/1539

**Comment by kocsismate** [comment]
I've removed "Returning a non-array from __sleep()" (https://github.com/php/doc-en/pull/1134) from the list, as it's a PHP 8.0 change. I'm closing the issue as all the tasks are now completed. Congrats to everyone involved!
